# Latest version: <URL TO CHECK FOR THE LATEST VERSION>
ENV <COMPILER_NAME>_VERSIONS 1.0 2.0 3.0
COPY compilers/<EDITION>/<COMPILER_NAME>/update.cron /cron/<COMPILER_NAME>
COPY compilers/<EDITION>/<COMPILER_NAME>/update.sh /update/<COMPILER_NAME>
RUN set -xe && \
    # INSTALLATION COMMANDS...
    apt-get autoremove --purge && \
    rm -rf /tmp/* /var/lib/apt/lists/*
