#!/bin/bash
set -e

if [[ ! -f /.dockerenv ]]; then
    echo "Tests should be run inside a Docker container. Use bin/run-tests script from the root of the project."
    exit -1
fi

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -l|--language)
            PREFERRED_LANGUAGE="$2"
            shift
            shift
        ;;
        --isolate)
            ISOLATE=true
            shift
        ;;
        *)
            echo "Unknown option $key"
            echo "Usage: ./run [--language <language>] [--isolate]"
            exit -1
        ;;
    esac
done

readonly LANG_PROPERTIES_FILE=lang.properties

for directory in *; do
    [[ ! -d $directory ]] && continue

    lang_properties=$directory/$LANG_PROPERTIES_FILE
    [[ ! -f $lang_properties ]] && continue

    [[ -v PREFERRED_LANGUAGE && $PREFERRED_LANGUAGE != $directory ]] && continue

    source $lang_properties
    for VERSION in $VERSIONS; do
        source $lang_properties

        echo "--- $NAME ---"
        cd $directory

        if [[ $ISOLATE == true ]]; then
            echo "Initializing isolate box."

            workdir="$(isolate --cg --init)"
            boxdir=$workdir/box
            echo "Using box directory $boxdir"

            cp $SOURCE_FILE $boxdir

            if [[ $COMPILE_CMD != "" ]]; then
                echo $COMPILE_CMD > $boxdir/compile

                echo "Compiling inside isolate."

                set +e
                isolate --cg -t 5 -x 2 -w 10 -k 128000 -p60 --cg-mem=256000 --cg-timing -f 4096 \
                        -E HOME=$workdir -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                        -E LANG -E LANGUAGE -E LC_ALL -d /etc:noexec --run -- /bin/bash compile

                if [[ $? != 0 ]]; then
                    echo "Running isolate cleanup"
                    isolate --cg --cleanup
                    rm -rf $workdir || true
                    exit -1
                fi

                set -e
            fi

            echo $RUN_CMD > $boxdir/run
            echo "world" > $workdir/stdin

            echo "Running inside isolate."

            set +e
            isolate --cg -t 2 -x 0.5 -w 5 -k 64000 -p30 --cg-mem=128000 --no-cg-timing -f 1024 \
                    -E HOME=$workdir -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                    -E LANG -E LANGUAGE -E LC_ALL -d /etc:noexec --run -- /bin/bash run < $workdir/stdin

            if [[ $? != 0 ]]; then
                exit_after_cleanup=true
            fi

            echo "Running isolate cleanup"
            isolate --cg --cleanup
            rm -rf $workdir || true
            [[ $exit_after_cleanup == true ]] && exit -1

            set -e
        else
            $COMPILE_CMD
            echo "world" | bash -c "$RUN_CMD"
            rm $(ls . | grep -v $SOURCE_FILE | grep -v $LANG_PROPERTIES_FILE) &> /dev/null || true
        fi

        cd ..
        echo
    done
done